export enum AssetType {
  CRYPTOCURRENCY = 'CRYPTOCURRENCY',
  STOCK = 'STOCK',
  ETF = 'ETF',
  MUTUAL_FUND = 'MUTUAL_FUND',
  BOND = 'BOND',
  COMMODITY = 'COMMODITY',
  FIAT = 'FIAT',
  NFT = 'NFT',
  DERIVATIVE = 'DERIVATIVE',
  LIQUIDITY_POOL = 'LIQUIDITY_POOL',
  STAKED_POSITION = 'STAKED_POSITION',
  LENDING_POSITION = 'LENDING_POSITION',
  OTHER = 'OTHER'
}