export enum IntegrationSource {
  // CEXs
  ROBINHOOD = 'ROBINHOOD',
  KRAKEN = 'KRAKEN',
  COINBASE = 'COINBASE',
  BINANCE = 'BINANCE',
  
  // DEXs
  UNISWAP = 'UNISWAP',
  SUSHISWAP = 'SUSHISWAP',
  PANCAKESWAP = 'PANCAKESWAP',
  CURVE = 'CURVE',
  BALANCER = 'BALANCER',
  
  // Wallets
  METAMASK = 'METAMASK',
  RABBY = 'RABBY',
  PHANTOM = 'PHANTOM',
  SLUSH = 'SLUSH',
  SUIET = 'SUIET',
  
  // Other
  MANUAL_ENTRY = 'MANUAL_ENTRY',
  BLOCKCHAIN_DIRECT = 'BLOCKCHAIN_DIRECT',
  OTHER = 'OTHER'
}